name: libxml2
builder:
  name: AutotoolsBuilder
  configure_options: --without-python --with-zlib=\${prefix}
platforms:
  - aix-6.1/powerpc
  - windows-2012/amd64
  - windows-2012/i386
  - linux-glibc2.11/amd64